export const PIKE_STATS = 'PIKE_STATS';
export const PIKE_DIRECTORS = 'PIKE_DIRECTORS';
export const PIKE_CACHED = 'PIKE_CACHED';
export const PIKE_CACHED_CLEAR = 'PIKE_CACHED_CLEAR';
export const PIKE_FETCHING = 'PIKE_FETCHING';
